<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('User', 'doctrine');

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $password
 * @property string $firstname
 * @property string $lastname
 * @property string $fullname
 * @property string $email
 * @property string $mobile
 * @property string $avator
 * @property integer $is_active
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $created_aid
 * @property integer $updated_aid
 * @property timestamp $logged_at
 * @property string $activation_code
 * @property string $ip
 * 
 * @method integer   getId()              Returns the current record's "id" value
 * @method string    getPassword()        Returns the current record's "password" value
 * @method string    getFirstname()       Returns the current record's "firstname" value
 * @method string    getLastname()        Returns the current record's "lastname" value
 * @method string    getFullname()        Returns the current record's "fullname" value
 * @method string    getEmail()           Returns the current record's "email" value
 * @method string    getMobile()          Returns the current record's "mobile" value
 * @method string    getAvator()          Returns the current record's "avator" value
 * @method integer   getIsActive()        Returns the current record's "is_active" value
 * @method timestamp getCreatedAt()       Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()       Returns the current record's "updated_at" value
 * @method integer   getCreatedAid()      Returns the current record's "created_aid" value
 * @method integer   getUpdatedAid()      Returns the current record's "updated_aid" value
 * @method timestamp getLoggedAt()        Returns the current record's "logged_at" value
 * @method string    getActivationCode()  Returns the current record's "activation_code" value
 * @method string    getIp()              Returns the current record's "ip" value
 * @method User      setId()              Sets the current record's "id" value
 * @method User      setPassword()        Sets the current record's "password" value
 * @method User      setFirstname()       Sets the current record's "firstname" value
 * @method User      setLastname()        Sets the current record's "lastname" value
 * @method User      setFullname()        Sets the current record's "fullname" value
 * @method User      setEmail()           Sets the current record's "email" value
 * @method User      setMobile()          Sets the current record's "mobile" value
 * @method User      setAvator()          Sets the current record's "avator" value
 * @method User      setIsActive()        Sets the current record's "is_active" value
 * @method User      setCreatedAt()       Sets the current record's "created_at" value
 * @method User      setUpdatedAt()       Sets the current record's "updated_at" value
 * @method User      setCreatedAid()      Sets the current record's "created_aid" value
 * @method User      setUpdatedAid()      Sets the current record's "updated_aid" value
 * @method User      setLoggedAt()        Sets the current record's "logged_at" value
 * @method User      setActivationCode()  Sets the current record's "activation_code" value
 * @method User      setIp()              Sets the current record's "ip" value
 * 
 * @package    imdb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('firstname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('lastname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('fullname', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('mobile', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('avator', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('is_active', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_aid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_aid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('logged_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('activation_code', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('ip', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}