<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('NewsItem', 'doctrine');

/**
 * BaseNewsItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $news_id
 * @property integer $item_id
 * @property integer $created_aid
 * @property integer $updated_aid
 * @property News $News
 * @property Item $Item
 * @property Admin $Admin
 * @property Admin $Admin_4
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method integer  getNewsId()      Returns the current record's "news_id" value
 * @method integer  getItemId()      Returns the current record's "item_id" value
 * @method integer  getCreatedAid()  Returns the current record's "created_aid" value
 * @method integer  getUpdatedAid()  Returns the current record's "updated_aid" value
 * @method News     getNews()        Returns the current record's "News" value
 * @method Item     getItem()        Returns the current record's "Item" value
 * @method Admin    getAdmin()       Returns the current record's "Admin" value
 * @method Admin    getAdmin4()      Returns the current record's "Admin_4" value
 * @method NewsItem setId()          Sets the current record's "id" value
 * @method NewsItem setNewsId()      Sets the current record's "news_id" value
 * @method NewsItem setItemId()      Sets the current record's "item_id" value
 * @method NewsItem setCreatedAid()  Sets the current record's "created_aid" value
 * @method NewsItem setUpdatedAid()  Sets the current record's "updated_aid" value
 * @method NewsItem setNews()        Sets the current record's "News" value
 * @method NewsItem setItem()        Sets the current record's "Item" value
 * @method NewsItem setAdmin()       Sets the current record's "Admin" value
 * @method NewsItem setAdmin4()      Sets the current record's "Admin_4" value
 * 
 * @package    imdb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNewsItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('news_item');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('news_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('item_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_aid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_aid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('News', array(
             'local' => 'news_id',
             'foreign' => 'id'));

        $this->hasOne('Item', array(
             'local' => 'item_id',
             'foreign' => 'id'));

        $this->hasOne('Admin', array(
             'local' => 'created_aid',
             'foreign' => 'id'));

        $this->hasOne('Admin as Admin_4', array(
             'local' => 'updated_aid',
             'foreign' => 'id'));
    }
}