<?php

/**
 * AdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Admin');
    }
    
    public function doExecute($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        
        return $q->execute();
    }
    
  
    public function doFetchArray($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
                
        return $q->fetchArray();
    }
    
    
    public function doFetchSelection($params = array())
    {
        $res = array();
        $rss = self::doFetchArray($params);
        foreach ($rss as $rs)
        {
          $res[$rs['id']] = $rs['title'];
        }
        return $res;
    }
    
    
    public function doFetchOne($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        return $q->fetchOne();
    }
    
  
    public function doCount($params = array())
    {
        $q = Doctrine_Query::create()->select('count(id)');
        $q = self::params($q, $params);
        return $q->count();
    }
    
    public function getPager($params = array(), $page=1)
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);

        $pager = new sfDoctrinePager('Admin', sfConfig::get('app_pager', 10));
        $pager->setPage($page);
        $pager->setQuery($q);
        $pager->init();
        
        return $pager;
    }
    
    
    private function params($q, $params = array())
    {
        $q->from('Admin');
  
        if(isset($params['id']) && $params['id'] != null)
            $q->andWhere('id = ?', $params['id']);
            
        if(isset($params['email']) && $params['email'] != null)
            $q->andWhere('email = ?', $params['email']);

        if(isset($params['keyword']) && $params['keyword'] != null)
            $q->andWhere('email LIKE ?', array('%'.$params['keyword'].'%'));
        
        if(isset($params['isActive'])) {
            if($params['isActive'] != "all" && in_array($params['isActive'], array('0', '1'))) // all ued filter hiihgui
                $q->andWhere('is_active = ?', $params['isActive']);
        } else {
            $q->andWhere('is_active = ?', 1);
        }

        // group, offset, limit, order
        if(isset($params['groupBy']) && $params['groupBy']) 
            $q->groupBy($params['groupBy']);

        if(isset($params['offset']) && $params['offset']) 
            $q->offset($params['offset']);    

        $limit = isset($params['limit']) ? $params['limit'] : sfConfig::get('app_limit', 30);
        $q->limit($limit);
        
        $order = isset($params['orderBy']) ? $params['orderBy'] : 'email ASC';
        $q->orderBy($order);
        
        return $q;
    }

}