<?php

/**
 * CinemaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CinemaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CinemaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Cinema');
    }
}