<?php

/**
 * Link
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Link extends BaseLink
{
    public function __toString() {
        $str = '';
        if($this->getSeason() == 100000) {
            $str .= 'Special';
        } else if($this->getSeason()) {
            $str .= 'S'.(strlen($this->getSeason()) == 1 ? '0' : '').$this->getSeason();
        }
        
        if($this->getEpisode()) {
            $str .= $str == 'Special' ? ' ' : '';
            $str .= $str ? 'E'.(strlen($this->getSeason()) == 1 ? '0' : '').$this->getEpisode() : '';
        }
        
        if($this->getTitle()) {
            $str .= $str ? ' ' : '';
            $str .= $this->getTitle();
        }
        return $str;
    }

}