<?php

/**
 * LoveTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LoveTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LoveTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Love');
    }
}