<?php

/**
 * SeriasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeriasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SeriasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Serias');
    }
}