# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        movie
    description:  movie
    keywords:     movie
    language:     en
    robots:       index, follow

  stylesheets:    [front.css, custom.css, other.css]

  javascripts:    []

  has_layout:     true
  layout:         layout