<?php

/**
 * BestsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BestsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BestsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Bests');
    }
}