<?php

/**
 * CelebrityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CelebrityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CelebrityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Celebrity');
    }
}