# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:      
      #dsn:      mysql:host=localhost;dbname=urinesse_imdb
      #username: urinesse_handaa
      #password: urinesse@handaa2013
      
      dsn:      mysql:host=localhost;dbname=tmp
      username: root
      password: <;(w3iF?Mc75!Tg